server:
  ip: localhost
  delegate-port: 8080
  image:
    name: image
    path: 'D:\first-mvc\UploadFile\${server.image.name}\'
  file:
    name: file
    path: 'D:\first-mvc\UploadFile\${server.file.name}\'
logging:
  level:
    sqltiming: DEBUG
    resultsettable: DEBUG
